version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: backend
    restart: always
    env_file: ./config/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.4
    container_name: db
    env_file: ./config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
