# Generated by Django 4.0.6 on 2022-07-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
