# Generated by Django 4.0.6 on 2022-07-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('images', '0002_alter_image_height_alter_image_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.useraccount'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to='static/images', width_field='width'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(height_field='height', upload_to='static/thumbnails', width_field='width'),
        ),
    ]
