# Generated by Django 4.0.6 on 2022-07-07 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_uploaded_by_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='images.image'),
        ),
        migrations.CreateModel(
            name='ImageAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires', models.DateTimeField()),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
        ),
    ]
