# Generated by Django 4.0.6 on 2022-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_thumbnail_image_imageaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to='images', width_field='width'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(height_field='height', upload_to='thumbnails', width_field='width'),
        ),
    ]
