# Generated by Django 4.0.6 on 2022-07-05 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('contains_original_link', models.BooleanField(default=False)),
                ('generates_expiring_link', models.BooleanField(default=False)),
                ('thumbnail_sizes', models.ManyToManyField(to='images.thumbnailsize')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
